### ISSUE TITLE
[feature request] add markdown table support

### ISSUE THREAD

**Issue by lifehackerhansol** [Epicpkmn11/pk11.us#4]
As of this moment, it "works".

By "works", I mean:
![image](https://github.com/Epicpkmn11/pk11.us/assets/37358975/0b6e758a-0b3d-47eb-a5de-f9e1cf38c5df)

I have no idea how to write CSS.

**Comment by Epicpkmn11** [comment]
All DS-Homebrew Wiki CSS added to here in c6dc86455e4d92a0e5b92d66cb92b6d49fb09639 for MIT licensing
